stages:
  - test

test:
  image: python:3.11.9
  before_script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
    - python manage.py migrate
    - python manage.py collectstatic --noinput --clear
  script:
    - pytest --disable-warnings
