# Generated by Django 5.1.7 on 2025-03-18 17:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("habit_id", models.AutoField(primary_key=True, serialize=False)),
                ("habit_name", models.CharField(max_length=255)),
                ("habit_description", models.TextField(blank=True, null=True)),
                (
                    "habit_occurrence",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="daily",
                        max_length=20,
                    ),
                ),
                ("habit_created_on", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Completion",
            fields=[
                ("completion_id", models.AutoField(primary_key=True, serialize=False)),
                ("completion_date", models.DateField(default=datetime.date.today)),
                (
                    "completion_habit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completions",
                        to="habits.habit",
                    ),
                ),
            ],
            options={
                "unique_together": {("completion_habit", "completion_date")},
            },
        ),
    ]
