# Generated by Django 5.1.7 on 2025-03-20 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_habit_habit_last_streak_habit_habit_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="completion",
            old_name="completion_habit",
            new_name="completion_habit_id",
        ),
        migrations.AlterUniqueTogether(
            name="completion",
            unique_together={("completion_habit_id", "completion_date")},
        ),
    ]
